secrets:
    dbUri: "${local.root_user}:${local.root_password}@tcp(${google_sql_database_instance.database.private_ip_address})/${google_sql_database.database.name}?charset=utf8&parseTime=True"
    encryptionPassphrase: "test"