kind: pipeline
name: default

steps:
  - name: wait_for_docker
    image: docker:dind
    commands:
      - sleep 20
  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - docker build -t "registry.dev.videocoin.net/iam:${DRONE_TAG}" .
  - name: push
    image: docker:dind
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - docker login -u $${USERNAME} -p $${PASSWORD} registry.dev.videocoin.net
      - docker push "registry.dev.videocoin.net/iam:${DRONE_TAG}"

volumes:
  - name: dockersock
    temp: {}

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

trigger:
  event:
    - tag
