---
kind: pipeline
type: kubernetes
name: cloud-iam

steps:
  - name: build-publish-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.videocoin.net
      repo: registry.videocoin.net/iam/iam
      tags: ${DRONE_TAG}

  - name: slack-notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: videocoin-monitoring
      link_names: true
      username: Drone
      template: >
        {{#success build.status}}
          The build number {{build.number}} from {{build.author_email}} to {{build.source_repo}} succeeded. Check details at https://drone.videocoin.net/{{build.source_repo}}
        {{else}}
          The build number {{build.number}} from {{build.author_email}} to {{build.source_repo}} failed. Check details at https://drone.videocoin.net/{{build.source_repo}}
        {{/success}}

trigger:
  event:
    - tag
