---
kind: pipeline
type: kubernetes
name: cloud-iam

steps:
  - name: tests
    image: golang:1.14
    commands:
      - go test ./... -v
      - sleep 20

  - name: build-publish-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: registry.videocoin.net
      repo: registry.videocoin.net/cloud-iam/iam
      tags: ${DRONE_TAG}

  - name: lint-chart
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./deployments/helm

  - name: publish-chart
    image: devth/helm:v3.1.1
    environment:
      USERNAME:
        from_secret: registry_username
      PASSWORD:
        from_secret: registry_password
    commands:
      - helm repo add iam https://registry.videocoin.net/chartrepo/cloud-iam --username $$USERNAME --password $$PASSWORD
      - helm plugin install https://github.com/chartmuseum/helm-push
      - helm push ./deployments/helm iam --username $$USERNAME --password $$PASSWORD

  - name: slack-notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: videocoin-monitoring
      link_names: true
      username: Drone
      template: >
        {{#success build.status}}
          The build number {{build.number}} from {{build.author_email}} to {{build.source_repo}} succeeded. Check details at https://drone.videocoin.net/{{build.source_repo}}
        {{else}}
          The build number {{build.number}} from {{build.author_email}} to {{build.source_repo}} failed. Check details at https://drone.videocoin.net/{{build.source_repo}}
        {{/success}}

trigger:
  event:
    - tag
