replicaCount: 1

image:
  repository: registry.dev.videocoin.net/iam/iam
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5000

#gateway:
#  hosts:
#  - iam.dev.videocoin.net
#  tls:
#    enabled: false
#    secretName: 

resources:
  {}
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  dbUri: "test:123456789@tcp(10.235.0.3)/test"
  encryptionPassphrase: "test"
