FROM golang:1.13 as builder

WORKDIR /github.com/videocoin/cloud-iam

COPY . .

RUN make admind

FROM bitnami/minideb:jessie

COPY --from=builder /github.com/videocoin/cloud-iam/build/bin/admind /usr/local/bin/

RUN install_packages curl

RUN GRPC_HEALTH_PROBE_VERSION=v0.3.0 && curl -L -k https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 --output /usr/local/bin/grpc_health_probe && chmod +x /usr/local/bin/grpc_health_probe

CMD ["admind"]