---
apiVersion: v1
kind: Secret
metadata:
  name: admin
  namespace: iam
  labels:
    app: admin
type: Opaque
data:
  dbUri: "dGVzdDoxMjM0NTY3ODlAdGNwKDEwLjIzNS4wLjMpL3Rlc3Q/Y2hhcnNldD11dGY4JnBhcnNlVGltZT1UcnVl" #test:123456789@tcp(10.235.0.3)/test?charset=utf8&parseTime=True

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: iam
  labels:
    app: admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
      version: v1
  template:
    metadata:
      labels:
        app: admin
        version: v1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: admin
          image: registry.dev.videocoin.net/iam/admin:v0.1.0-dev.18
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 5000
          livenessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:5000"]
            initialDelaySeconds: 5
          readinessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:5000"]
            initialDelaySeconds: 10
          env:
            - name: admin_DBURI
              valueFrom:
                secretKeyRef:
                  name: admin
                  key: dbUri
      volumes:
        - name: secrets
          secret:
            secretName: admin

---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: iam
  labels:
    app: admin
spec:
  ports:
    - name: grpc
      port: 5000
  selector:
    app: admin
