---
apiVersion: v1
kind: Namespace
metadata:
  name: iam
  namespace: iam
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Secret
metadata:
  name: iam
  namespace: iam
  labels:
    app.kubernetes.io/name: iam
type: Opaque
data:
  dbUri: "dGVzdDoxMjM0NTY3ODlAdGNwKDEwLjIzNS4wLjMpL3Rlc3Q=" #test:123456789@tcp(10.235.0.3)/test
  encryptionPassphrase: "dGVzdA==" #test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: iam
  labels:
    app.kubernetes.io/name: iam
    app.kubernetes.io/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iam
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iam
        app.kubernetes.io/version: v1
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: iam
          image: registry.dev.videocoin.net/iam/iam:v0.1.0-dev.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 5000
          livenessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:5000"]
            initialDelaySeconds: 5
          readinessProbe:
            exec:
              command: ["grpc_health_probe", "-addr=:5000"]
            initialDelaySeconds: 10
          env:
            - name: IAM_DBURI
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: dbUri
            - name: IAM_ENCRYPTIONPASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: encryptionPassphrase
      volumes:
        - name: secrets
          secret:
            secretName: iam

---
apiVersion: v1
kind: Service
metadata:
  name: iam
  namespace: iam
  labels:
    app.kubernetes.io/name: iam
spec:
  ports:
    - name: grpc
      port: 5000
  selector:
    app.kubernetes.io/name: iam
