apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "iam.fullname" . }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
  {{- with .Values.gateway.hosts }}
    hosts:
      {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- if .Values.gateway.tls.enabled }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
  {{- with .Values.gateway.hosts }}
    hosts:
      {{- toYaml . | nindent 8 }}
  {{- end }}
    - "*"
    tls:
      mode: SIMPLE
      #credentialName
  {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "iam.fullname" . }}
  labels:
    {{- include "iam.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "iam.fullname" . }}
  http:
  - route:
    - destination:
        host: {{ include "iam.fullname" . }}
        port:
          number: {{ .Values.service.port }}